/**
 * @file pins.h
 * @brief GPIO pin definitions for SEDU Single-PCB Feed Drill
 * 
 * Project: SEDU Single-PCB Feed Drill
 * Revision: C.4b
 * 
 * AUTO-GENERATED from design_database.yaml
 * Generated: 2025-11-14 18:52:14
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit design_database.yaml and run: python scripts/generate_all.py
 */

#ifndef PINS_H
#define PINS_H

// Motor Control
// ----------------------------------------------------------------------
#define MOTOR_HS_U           38   // Motor high-side U PWM
#define MOTOR_LS_U           39   // Motor low-side U PWM
#define MOTOR_HS_V           40   // Motor high-side V PWM
#define MOTOR_LS_V           41   // Motor low-side V PWM
#define MOTOR_HS_W           42   // Motor high-side W PWM
#define MOTOR_LS_W           43   // Motor low-side W PWM

// Motor Sensing
// ----------------------------------------------------------------------
#define CSA_U                5    // Motor phase U current sense
#define CSA_V                6    // Motor phase V current sense
#define CSA_W                7    // Motor phase W current sense

// Hall Sensors
// ----------------------------------------------------------------------
#define HALL_U               8    // Motor Hall sensor U
#define HALL_V               9    // Motor Hall sensor V
#define HALL_W               13   // Motor Hall sensor W

// Actuator
// ----------------------------------------------------------------------
#define ACT_IPROPI           2    // DRV8873 current feedback
#define ACT_PH               30   // DRV8873 phase input
#define ACT_EN               31   // DRV8873 enable (PWM)

// Buttons
// ----------------------------------------------------------------------
#define BTN_START            23   // Start button (discrete, redundant)
#define BTN_STOP             24   // Stop button (discrete, NC, redundant)

// Battery/Ladder
// ----------------------------------------------------------------------
#define V_BAT_SENSE          1    // Battery voltage (140k/10k divider)
#define LADDER_SENSE         4    // Button ladder voltage

// SPI (DRV8353)
// ----------------------------------------------------------------------
#define DRV_MOSI             17   // DRV8353 SPI MOSI
#define DRV_SCK              18   // DRV8353 SPI clock
#define DRV_MISO             21   // DRV8353 SPI MISO
#define DRV_CS               22   // DRV8353 SPI chip select

// SPI (LCD)
// ----------------------------------------------------------------------
#define LCD_CS               16   // LCD chip select
#define LCD_DC               32   // LCD data/command
#define LCD_RST              33   // LCD reset
#define LCD_BL               34   // LCD backlight PWM

// USB
// ----------------------------------------------------------------------
#define USB_DM               19   // USB D- (22Ω series)
#define USB_DP               20   // USB D+ (22Ω series)

// Fault Monitoring
// ----------------------------------------------------------------------
#define DRV8353_nFAULT       11   // DRV8353 fault (open-drain, 10k pullup)
#define DRV8873_nFAULT       12   // DRV8873 fault (open-drain, 10k pullup)
#define LM5069_PGD           14   // LM5069 power good (open-drain, 100k pullup)

// User Feedback
// ----------------------------------------------------------------------
#define LED_STATUS           3    // Status LED
#define BUZZER               15   // Buzzer output

// Future
// ----------------------------------------------------------------------
#define NTC_TEMP             10   // NTC temperature sensor (future)

#endif // PINS_H