#!/usr/bin/env python3
"""
Generate Component Report (Component_Report.md) from design_database.yaml

This script creates the component report markdown from the single-source database.
DO NOT edit Component_Report.md directly - edit design_database.yaml and regenerate.
"""

import sys
from pathlib import Path
import yaml
from datetime import datetime


def load_database():
    """Load design database from YAML."""
    db_path = Path(__file__).parent.parent / "design_database.yaml"
    with open(db_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def generate_component_report():
    """Generate Component Report from design database."""
    db = load_database()
    components = db.get('components', {})
    ics = db.get('ics', {})
    metadata = db.get('metadata', {})

    report_path = Path(__file__).parent.parent / "Component_Report.md"

    lines = []
    lines.append("# SEDU Single-PCB Component Report")
    lines.append("")
    lines.append(f"**Project:** {metadata.get('project', 'SEDU')}")
    lines.append(f"**Revision:** {metadata.get('revision', 'C.4b')}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("**AUTO-GENERATED from design_database.yaml**")
    lines.append("")
    lines.append("DO NOT EDIT THIS FILE DIRECTLY - Edit design_database.yaml and run: `python scripts/generate_all.py`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # IC Summary
    lines.append("## Major ICs")
    lines.append("")
    for ic_ref, ic_data in sorted(ics.items()):
        lines.append(f"### {ic_ref}: {ic_data['part']}")
        lines.append(f"- **Manufacturer:** {ic_data['manufacturer']}")
        lines.append(f"- **Description:** {ic_data['description']}")
        if 'supply_voltage' in ic_data:
            lines.append(f"- **Supply Voltage:** {ic_data['supply_voltage']}V")
        if 'supply_voltage_vm' in ic_data:
            vm = ic_data['supply_voltage_vm']
            lines.append(f"- **VM Range:** {vm[0]}V - {vm[1]}V")
        if 'supply_voltage_dvdd' in ic_data:
            lines.append(f"- **DVDD:** {ic_data['supply_voltage_dvdd']}V")
        if 'output_voltage' in ic_data:
            lines.append(f"- **Output Voltage:** {ic_data['output_voltage']}V")
        if 'output_current' in ic_data:
            lines.append(f"- **Output Current:** {ic_data['output_current']}A")
        if 'datasheet' in ic_data:
            lines.append(f"- **Datasheet:** {ic_data['datasheet']}")
        if 'notes' in ic_data:
            lines.append(f"- **Notes:** {ic_data['notes']}")
        lines.append("")

    # Critical Components by IC
    lines.append("---")
    lines.append("")
    lines.append("## Critical Components by IC")
    lines.append("")

    # Group components by IC
    components_by_ic = {}
    for ref, comp_data in components.items():
        ic = comp_data.get('ic', 'Other')
        if ic not in components_by_ic:
            components_by_ic[ic] = []
        components_by_ic[ic].append((ref, comp_data))

    for ic_ref in sorted(components_by_ic.keys()):
        # Get IC name
        ic_name = ics.get(ic_ref, {}).get('part', ic_ref)
        lines.append(f"### {ic_ref}: {ic_name}")
        lines.append("")

        # Table header
        lines.append("| Ref | Value | Part Number | Description | Criticality |")
        lines.append("|-----|-------|-------------|-------------|-------------|")

        for ref, comp_data in sorted(components_by_ic[ic_ref]):
            value = comp_data.get('value', '-')
            part_num = comp_data.get('part_number', 'TBD')
            desc = comp_data.get('description', '')
            crit = comp_data.get('criticality', 'NORMAL')

            # Truncate long part numbers
            if len(part_num) > 20:
                part_num = part_num[:17] + "..."

            # Truncate long descriptions
            if len(desc) > 40:
                desc = desc[:37] + "..."

            lines.append(f"| {ref} | {value} | {part_num} | {desc} | {crit} |")

        lines.append("")

        # Add notes for critical components
        critical_comps = [(ref, comp_data) for ref, comp_data in components_by_ic[ic_ref]
                          if comp_data.get('criticality') == 'CRITICAL']

        if critical_comps:
            lines.append("**Critical Component Details:**")
            lines.append("")
            for ref, comp_data in critical_comps:
                lines.append(f"- **{ref}**: {comp_data.get('description', '')}")
                if 'calculation' in comp_data:
                    lines.append(f"  - Calculation: {comp_data['calculation']}")
                if 'datasheet_ref' in comp_data:
                    lines.append(f"  - Datasheet: {comp_data['datasheet_ref']}")
                if 'notes' in comp_data:
                    lines.append(f"  - Notes: {comp_data['notes']}")
            lines.append("")

    # Locked Values
    lines.append("---")
    lines.append("")
    lines.append("## Locked Design Values")
    lines.append("")
    lines.append("These values are **FROZEN** and should not be changed without updating frozen state:")
    lines.append("")

    locked_comps = [(ref, comp_data) for ref, comp_data in components.items()
                    if comp_data.get('locked', False)]

    if locked_comps:
        lines.append("| Ref | Value | Reason |")
        lines.append("|-----|-------|--------|")
        for ref, comp_data in sorted(locked_comps):
            value = comp_data.get('value', '-')
            calc = comp_data.get('calculation', comp_data.get('description', ''))
            lines.append(f"| {ref} | {value} | {calc} |")
        lines.append("")
    else:
        lines.append("No locked components defined.")
        lines.append("")

    # Write file
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated Component Report with {len(ics)} ICs and {len(components)} components")
    return 0


if __name__ == "__main__":
    try:
        generate_component_report()
        sys.exit(0)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
