#!/usr/bin/env python3
"""
Generate pins.h (firmware/include/pins.h) from design_database.yaml

This script creates the firmware GPIO pin definitions from the single-source database.
DO NOT edit pins.h directly - edit design_database.yaml and regenerate.
"""

import sys
from pathlib import Path
import yaml
from datetime import datetime


def load_database():
    """Load design database from YAML."""
    db_path = Path(__file__).parent.parent / "design_database.yaml"
    with open(db_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def generate_pins_h():
    """Generate pins.h from design database."""
    db = load_database()
    gpio_pins = db.get('gpio_pins', {})
    metadata = db.get('metadata', {})

    pins_h_path = Path(__file__).parent.parent / "firmware" / "include" / "pins.h"

    # Group pins by function
    groups = {
        'Motor Control': [],
        'Motor Sensing': [],
        'Hall Sensors': [],
        'Actuator': [],
        'Buttons': [],
        'Battery/Ladder': [],
        'SPI (DRV8353)': [],
        'SPI (LCD)': [],
        'USB': [],
        'Fault Monitoring': [],
        'User Feedback': [],
        'Future': []
    }

    for gpio_num, pin_data in sorted(gpio_pins.items(), key=lambda x: int(x[0].replace('GPIO', ''))):
        function = pin_data['function']
        description = pin_data.get('description', '')
        gpio_int = gpio_num.replace('GPIO', '')

        # Categorize
        if 'MOTOR_HS' in function or 'MOTOR_LS' in function:
            groups['Motor Control'].append((function, gpio_int, description))
        elif 'CSA_' in function:
            groups['Motor Sensing'].append((function, gpio_int, description))
        elif 'HALL_' in function:
            groups['Hall Sensors'].append((function, gpio_int, description))
        elif 'ACT_' in function:
            groups['Actuator'].append((function, gpio_int, description))
        elif 'BTN_' in function:
            groups['Buttons'].append((function, gpio_int, description))
        elif 'V_BAT' in function or 'LADDER' in function:
            groups['Battery/Ladder'].append((function, gpio_int, description))
        elif 'DRV_' in function:
            groups['SPI (DRV8353)'].append((function, gpio_int, description))
        elif 'LCD_' in function:
            groups['SPI (LCD)'].append((function, gpio_int, description))
        elif 'USB_' in function:
            groups['USB'].append((function, gpio_int, description))
        elif 'nFAULT' in function or 'PGD' in function:
            groups['Fault Monitoring'].append((function, gpio_int, description))
        elif 'BUZZER' in function or 'LED_' in function:
            groups['User Feedback'].append((function, gpio_int, description))
        elif 'NTC_' in function or 'future' in description.lower():
            groups['Future'].append((function, gpio_int, description))

    # Generate header file
    lines = []
    lines.append("/**")
    lines.append(" * @file pins.h")
    lines.append(" * @brief GPIO pin definitions for SEDU Single-PCB Feed Drill")
    lines.append(" * ")
    lines.append(f" * Project: {metadata.get('project', 'SEDU')}")
    lines.append(f" * Revision: {metadata.get('revision', 'C.4b')}")
    lines.append(" * ")
    lines.append(" * AUTO-GENERATED from design_database.yaml")
    lines.append(f" * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(" * ")
    lines.append(" * DO NOT EDIT THIS FILE DIRECTLY")
    lines.append(" * Edit design_database.yaml and run: python scripts/generate_all.py")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef PINS_H")
    lines.append("#define PINS_H")
    lines.append("")

    # Generate pin definitions by group
    for group_name, pins in groups.items():
        if not pins:
            continue

        lines.append(f"// {group_name}")
        lines.append("// " + "-" * 70)

        for function, gpio_int, description in pins:
            # Format: #define MOTOR_HS_U 38  // Motor high-side U PWM
            # Use function name as-is (preserves nFAULT vs NFAULT)
            lines.append(f"#define {function:20s} {gpio_int:3s}  // {description}")

        lines.append("")

    lines.append("#endif // PINS_H")

    # Write file
    pins_h_path.parent.mkdir(parents=True, exist_ok=True)
    with open(pins_h_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"Generated pins.h with {len(gpio_pins)} GPIO definitions")
    return 0


if __name__ == "__main__":
    try:
        generate_pins_h()
        sys.exit(0)
    except Exception as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
